FROM whanos-java AS builder
USER root
WORKDIR /app

# Copy source code
COPY app/ .

# Build the application with Maven
RUN mvn -f pom.xml clean package && \
    cp target/*.jar app.jar

# Ensure the built JAR exists
RUN test -f app.jar

FROM whanos-java
COPY --from=builder /app/app.jar /app/app.jar

WORKDIR /app
# Execution command
CMD ["java", "-jar", "app.jar"]
