FROM gcc:13.2

RUN apt-get update && \
    apt-get install -y --no-install-recommends make build-essential \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Default command (can be overridden)
CMD ["/bin/bash"]
