FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y \
    curl ca-certificates \
    xz-utils bash sudo \
    && rm -rf /var/lib/apt/lists/*

RUN useradd -m nixuser && \
    echo "nixuser ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers && \
    su nixuser -c "curl -L https://nixos.org/nix/install | sh"

ENV USER=nixuser
ENV HOME=/home/$USER
ENV PATH=$HOME/.nix-profile/bin:$HOME/.nix-profile/sbin:$HOME/.local/bin:$HOME/bin:$PATH
ENV NIX_PATH=nixpkgs=$HOME/.nix-defexpr/channels/nixpkgs

SHELL ["/bin/bash", "-c"]
USER nixuser

RUN mkdir -p $HOME/.config/nix \
    && echo "experimental-features = nix-command flakes" \
    | tee $HOME/.config/nix/nix.conf

CMD [ "nix-shell", "-p", "bash" ]
