#!/usr/bin/env python
"""
Build base Docker images contained in the images/ directory.

Usage:
    python base_build.py [all|<lang> ...]

default:
    build only the foundation image

args:
    all - build all base images
    <lang> - build only the base image for the specified language
    -h, --help - show this help message and exit
"""
import subprocess
import sys
from pathlib import Path

IMAGES_DIR = Path("./images")
FOUNDATION_IMAGE = (IMAGES_DIR / "Dockerfile.foundation", "whanos-foundation")

if "-h" in sys.argv or "--help" in sys.argv:
    print(__doc__)
    sys.exit(0)

subprocess.run(
    ["docker", "build", "-t", FOUNDATION_IMAGE[1], "-"],
    input=FOUNDATION_IMAGE[0].read_bytes(),
    check=True
)

for dir_path in IMAGES_DIR.iterdir():
    if not dir_path.is_dir():
        continue

    if not ("all" in sys.argv or dir_path.name in sys.argv):
        continue

    dockerfile = dir_path / "Dockerfile.base"
    if not dockerfile.is_file():
        continue

    lang = dir_path.name
    print(f"Building base image for {lang}...")
    try:
        subprocess.run(
            ["docker", "build", "-t", f"whanos-{lang}", "-"],
            input=dockerfile.read_bytes(),
            check=True
        )
    except subprocess.CalledProcessError as e:
        print(f"Error building whanos-{lang}: {e}")
        continue

    print(f"Built whanos-{lang}\n")
