#!/usr/bin/env python
import subprocess
from pathlib import Path

IMAGES_DIR = Path("./images")
FOUNDATION_IMAGE = (IMAGES_DIR / "Dockerfile.foundation", "whanos-foundation")

subprocess.run(
    ["docker", "build", "-t", FOUNDATION_IMAGE[1], "-"],
    input=FOUNDATION_IMAGE[0].read_bytes(),
    check=True
)

for dir_path in IMAGES_DIR.iterdir():
    if not dir_path.is_dir():
        continue

    dockerfile = dir_path / "Dockerfile.base"
    if not dockerfile.is_file():
        continue

    lang = dir_path.name
    print(f"Building base image for {lang}...")
    try:
        subprocess.run(
            ["docker", "build", "-t", f"whanos-{lang}", "-"],
            input=dockerfile.read_bytes(),
            check=True
        )
    except subprocess.CalledProcessError as e:
        print(f"Error building whanos-{lang}: {e}")
        continue

    print(f"Built whanos-{lang}\n")
