services:
  jenkins:
    build:
      context: ../../
      dockerfile: infra/jenkins/Dockerfile
      args:
        DOCKER_GID: ${DOCKER_GID}
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - ./jenkins.yaml:/var/jenkins_home/casc_configs/jenkins.yaml:ro
      - ./../..:/workspace
      - ./../../befunge:/befunge
      - /var/run/docker.sock:/var/run/docker.sock # Docker in docker
      - ../../images:/images
    environment:
      - JENKINS_UID=1000
      - JENKINS_GID=1000
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc_configs/jenkins.yaml
      - DOCKER_GID=${DOCKER_GID}
    env_file:
      - .env
    user: "1000:1000"
    group_add:
      - "${DOCKER_GID}"
    restart: unless-stopped
