jenkins:
  systemMessage: "🚀 Welcome to Whanos Jenkins!"
  numExecutors: 2
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          name: "admin"
          password: "${ADMIN_PASSWORD}"

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

appearance:
  themeManager:
    disableUserThemes: true
    theme: "catppuccinMocha"

unclassified:
  location:
    url: http://localhost:8080/
