jenkins:
  systemMessage: "🚀 Welcome to Whanos Jenkins!"
  numExecutors: 2
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          name: "admin"
          password: "${ADMIN_PASSWORD}"

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

jobs:
  - file: /usr/share/jenkins/ref/init.groovy.d/job_dsl.groovy

appearance:
  themeManager:
    disableUserThemes: true
    theme: "catppuccinMocha"

unclassified:
  location:
    url: http://localhost:8080/

security:
  scriptApproval:
    approvedScriptHashes:
      - "SHA512:eb6ddc115541e8f2c7d8459abbfc8dc262d6d6b711371a2764e05ce9492ca18c50002afe65635480dbc0509c0d8acaf8ba73d42450fe518816d3b45fd79d9088"
    forceSandbox: false
